### ISSUE TITLE
Should Percentage be Numeric?

### ISSUE THREAD

**Issue by iamvery** [readysteady/percentage#5]
Thank you for the helpful library! I was recently investigating using it in place of our own internal implementation.

One issue that I ran into is that `Percentage` instances can't be used directly in arithmetic with Ruby `Money`, because they implement [type checking](https://github.com/RubyMoney/money/blob/faa0323e45b608c3a0540be6d059b9fb0debde26/lib/money/money/arithmetic.rb#L154). It took me a couple tries to get the behavior I wanted:

```ruby
Money.new(10) * Percentage.new(10) # expecting => #<Money 1>
=> TypeError: Can't multiply a Money by a Percentage's value
```

then

```ruby
Money.new(10) * Percentage.new(10).to_f # expecting => #<Money 1>
=> #<Money 100>
```

finally

```ruby
Money.new(10) * Percentage.new(10).to_r
=> #<Money 1>
```

So I suppose I have a couple questions:

1. Have you considered making `Percentage` a subclass of `Numeric` since it does represent a numeric value? I believe you already have the required interfaces implemented (arithmetic and `coerce`).
2. I was surprised that the floating point conversion of a `Percentage` is not the percentage in decimal form. Why is that the case?

Thank you again for taking the time to read this, and thank you for maintaining a useful library ❤️💙💚💛💜

**Comment by timcraft** [comment]
@iamvery You're welcome, and thanks! Glad you find it useful 😊

This isn't an issue I've run into myself because I usually use BigDecimal for money calculations.

To answer your questions:

1. No I hadn't considered that. I agree that makes sense conceptually (and the same argument could be made for Money), but the Numeric module comes with a lot of additional functionality which might not make sense for percentages, and I don't think it's as simple as just overriding a few methods. You're welcome to take a stab at it and see how that works, but I wouldn't want to add/maintain a large number of additional methods just for interoperability with another gem.

2. For consistency with #to_i. If #to_i operated on the fractional value it would always return zero, and given the behaviour of #to_i it would be surprising if #to_f returned something different. I didn't give it much thought originally because I don't use floats much. That ambiguity/confusion might be a good case for removing #to_f, for now you can do `percentage.to_r.to_f`

It would be awesome if your first example just worked. The "Ruby way" would be to use duck typing instead of type checking. A two line patch to Money::Arithmetic#* would do it:

```ruby
elsif value.respond_to?(:to_r)
  self.class.new(fractional * value.to_r, currency, bank)
```

Or something equivalent in Money::Arithmetic#coerce if that's a better place to put it. Using #to_r isn't specific to percentage and would support other classes.

I'd be happy to accept any similar patches to percentage, but if you're multiplying something by a percentage it's usually an object of the other class you want.

**Comment by iamvery** [comment]
I agree that you should not feel compelled outright to make updates for interoperability with a specific use case like this. The experience got me thinking about what the right solution to the problem would be and more generally how interchangeable `Percentage`s should be as a numeric value in its own rite. Ultimately it may even be that `Money` isn't "numeric enough" ¯\_(ツ)_/¯. 

Anyway, this was ultimately opened to satisfy my curiosity which you did robustly with your generous reply. Thank you for taking the time!

**Comment by timcraft** [comment]
It's helpful to consider different possibilites.

Interoperability is good to have. Small tweaks and additions are no problem (e.g. I'd add #to_r if it didn't already exist, I'd add #to_d if it was more broadly used), but subclassing Numeric is a heavy/complex change relatively, patching Money would be much simpler.
