### ISSUE TITLE
Error on `change` method ZeroDivisionError: divided by 0 

### ISSUE THREAD

**Issue by vinay57565** [readysteady/percentage#6]
I am using this gem to calculate the percentage but getting error sometimes when the min value is o, for example
```
percentage = Percentage.change(0, 1)
```
in that case I am getting error like 
```
ZeroDivisionError: divided by 0
from /usr/local/bundle/gems/percentage-1.4.1/lib/percentage.rb:118:in `/'
```

if you can manage it in some good manner so that can be easy to handle from the developers end.

**Comment by timcraft** [comment]
Yes—percentage change isn't defined when the starting value is zero, so that is something you need to handle in the calling code. Something like this logic:

```ruby
if old_value.zero?
  # A special value to represent undefined
else
  Percentage.change(old_value, new_value)
end
```

Depending on the context you might want to show *nothing* and omit the result entirely, or show *something* to visually indicate that the change is not defined (`n/a`, `NaN`, `—` etc).

To make this a bit easier I've changed the method to return nil instead of the exception, so you can now do this:

```ruby
Percentage.change(old_value, new_value) || "⚠️"
```

Available in version 2.0.0
